### ISSUE TITLE
merging overlapping/touching IP-blocks

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#100]
- [x]               Please open an issue on merging overlapping/touching IP-blocks. It can improve results here. E.g., replacing `161.26.0.0/16,161.27.0.0/16` with `161.26.0.0/15`
_Originally posted by @zivnevo in https://github.com/np-guard/vpc-network-config-analyzer/pull/95#discussion_r1254196729_

- [x] grouping of ip-blocks should be always applied

**Comment by ShiriMoran** [comment]
2nd item solved by #119

**Comment by ShiriMoran** [comment]
3rd item solved by #132
