### ISSUE TITLE
vpcModel: suggested changes to abstractions

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-analyzer#11]
- [ ] Currently a Node interface has a Cidr(). If we assume that a node is always a single address then we should change this to Address().
- [x] Make ExternalNetwork an abstract type
- [x] Add uid to all abstractions
- [x] consider renaming VPCConfig to something like CloudConfig, because it may contain several VPCs and the gateways between them

**Comment by zivnevo** [comment]
@kyorav @adisos , can we close this issue?

**Comment by kyorav** [comment]
yes
