### ISSUE TITLE
drawio output crashes

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-analyzer#112]
The attached config_object causes the tool to crash when invoked as follows:
```vpcanalyzer -vpc-config config_object.json -analysis-type all_endpoints -format arch_drawio ```
[crashes_drawio_config_object.txt](https://github.com/np-guard/vpc-network-config-analyzer/files/12143349/crashes_drawio_config_object.txt)

**Comment by haim-kermany** [comment]
סתם מלכלכים על drawio

**Comment by kyorav** [comment]
verified that it no longer crashes
