### ISSUE TITLE
Add a warning for useless sg rules based on the VPC APs

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#115]
1. The input file does not contain "list" of address prefixes, thus it does not know what is the address prefixes of the VPCs.
2. [Private addresses](https://phoenixnap.com/kb/public-vs-private-ip-address)  are considered private by the analyzer

Thus, there could be sg's rules referring solely to private address that are not within the VPC. At the current setting the analyzer will not be able to identify them since the address prefixes are not known to it. Perhaps it makes sense to add warning for these cases as they may indicate a mistake.

Priority: nice to have

**Comment by ShiriMoran** [comment]
Seems this is since the above cidr was identified as a private addredd https://phoenixnap.com/kb/public-vs-private-ip-address

**Comment by zivnevo** [comment]
Probably part of #116

**Comment by ShiriMoran** [comment]
solved by #731
