### ISSUE TITLE
simplify connection-sets output 

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#117]
example:

`protocol: TCP src-ports: 1-442,444-65535 dst-ports: 443; protocol: TCP src-ports: 443`

should be simplified to

`protocol: TCP dst-ports: 443; protocol: TCP src-ports: 443`

explore other examples to generalize the problem

**Comment by zivnevo** [comment]
Should probably move this issue to `models` repo

**Comment by zivnevo** [comment]
Move to `models` repo. See [here](https://github.com/np-guard/models/issues/58)
