### ISSUE TITLE
drawio output - changes for public network and IBM Cloud

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-analyzer#126]
Two modifications:

1. The VPC rectangle should be contained in an "IBM Cloud" rectangle.
2. The "public network" rectangle should be to the left of "IBM Cloud" (not containing anything)

See standard examples in the official repo: https://github.ibm.com/ibmcloud/ibm-cloud-stencils#v20-examples

**Comment by haim-kermany** [comment]
1. i see in the example the hierarchy:
IBM cloud -> Region -> ibm vpc -> zone -> subnet
should I add also Region?

**Comment by kyorav** [comment]
We can, but we don't have to, and it is not a trivial addition. You can see in the examples that it is OK to skip levels (the IKS example drops the VPC). As long as we are looking at only one VPC the region is not crucial information. 
However, to add it we will need to reverse engineer the region from the zones that appear in the VPC (because the region is not a property of a VPC configuration object). And if we don't want to rely on naming conventions we will need to use the API to get the list of regions and zones.

I suggest handling the region in a separate issue that will wait until we have stakeholder feedback saying they want it.
