### ISSUE TITLE
grouping api for drawio

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#144]
for Endpoint Iterface please add:
1. Names() (string, []strings) - will return the the name, without "public Network", and detailed list of names
2.   an interface to get the type.  please notice that the actual type can be from the ibmvpc pkg, so I can not read the type in my code 

for GroupedConnLine:
1.  does the connection allowing all connections
2. nice connection name, without "protocol:"

**Comment by haim-kermany** [comment]
one more important thing:
please do not allow two different endpoints representing the same set of nodes

**Comment by ShiriMoran** [comment]
Item 2 for Endpoint interface: why not use `type switches`? this seems to be what you need, and will get you the same answer I can produce

**Comment by haim-kermany** [comment]
1. grouping code is at vpcmodel package. also the drawiooutput code is at vpcmodel package. however, the types of EndpointElem are from ibmvpc package. vpcmodel can not import ibmvpc
2. yes, I need to know about connections between vsis in the subnet

**Comment by ShiriMoran** [comment]
> for Endpoint Iterface please add:
> 
>     1. Names() (string, []strings) - will return the the name, without "public Network", and detailed list of names
Why do you need the additional string? This is what Name() already returns
How about: 
`Names() []strings` will return a detailed list of names,  without "public Network" (if the network interface presents a single element then the array will be of length 1)

**Comment by haim-kermany** [comment]
the string should be a short representing label, to put under the icon. Name() can return a long string. 
"all ranges" is a good name. also need a good short name for a list of cidrs that are not "all ranges"

**Comment by haim-kermany** [comment]
its a boolean on the conn string. if the label is "alla connection", it should return true

**Comment by ShiriMoran** [comment]
> its a boolean on the conn string. if the label is "alla connection", it should return true

ahh. So you don't care if the connection is from/to all subnets/all vsis in a subnet (kitbag question, I know)

**Comment by haim-kermany** [comment]
can we use Kind(), and remove Type()

**Comment by zivnevo** [comment]
From today discussion:
* The `DetailsMap` mechanism used today is going to be hard to continue with.
* From a software engineering perspective, we mix in `drawioOutput.go` abstract and concrete (vendor-specific) implementations. Moreover, in the abstract library we rely on strings that are defined in the concrete library. This is going to bite us in the future.
* Suggested to replace `DetailsMap()` method with `DrawioTreeNode()` method such that each concrete resource will now how to produce its corresponding graphical element. If there is general code that is not vendor specific, it can remain in `drawioOutput.go`.
* Should check how `groupedEndpointsElems` and `groupedExternalNodes` fit into this story. What is the right TreeNode for them? This needs more experimentation.

**Comment by adisos** [comment]
The refactoring with DrawioTreeNode() method for each concrete resource was added in PR https://github.com/np-guard/vpc-network-config-analyzer/pull/165
