### ISSUE TITLE
support semantic-diff for analysis type "all_subnets"

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#163]
initial: diff over "all_subnets" analysis type

**Comment by ShiriMoran** [comment]
** under construction - do not disturb/comment yet**

Three stage:
1. Compute each of the connectivity maps separately
1. Compute the difference
1. Print the difference

**Comment by ShiriMoran** [comment]
After a meeting with Adi and Ziv:
* Computing the diff between `CloudConfigs` that will yield the correct `diff` analysis results is far too complicated. The diff will be computed on the analysis result.
* Two diffs will be computed, one in each direction.
* A diff should include the following information:
    * The source of the diff: missing connection or missing subnet/vsi
    * The type of the diff, given that relevant endpoints exists in both configurations:
                * missing connection
                * changed connection

**Comment by ShiriMoran** [comment]
High level flow:
1. Compute the relevant connectivity analysis for each of the configurations, call it `A` and `B`
1. Compute `A/B` and `B/A`
1. Print  `A/B` and `B/A`

Comments:
The result of 2 should be a struct based on the existing connectivity analysis struct
The printing and grouping should be based on these existing functionalities
Most of the effort here should be spent in writing the required functionality for 2

Next step:
Define the extended structs and functionality

**Comment by ShiriMoran** [comment]
PR #203 pr #206 along with adding command line support and end to end test will close this PR

**Comment by ShiriMoran** [comment]
follow up issues:
https://github.com/np-guard/vpc-network-config-analyzer/issues/199
https://github.com/np-guard/vpc-network-config-analyzer/issues/209
https://github.com/np-guard/vpc-network-config-analyzer/issues/210

And:
https://github.com/np-guard/vpc-network-config-analyzer/issues/211

**Comment by ShiriMoran** [comment]
solved by #203 #206 #220 #223
follow ups: issues #209 #210 #228
