### ISSUE TITLE
support multi-vpc config analysis output with drawio

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#225]
@haim-kermany, is there a way to have multiple diagrams in a single .drawio file?

_Originally posted by @zivnevo in https://github.com/np-guard/vpc-network-config-analyzer/pull/207#discussion_r1378639410_

**Comment by haim-kermany** [comment]
it is possible to have multi diagrams in one file
it is also possible  to have multi vpc on one diagram

**Comment by haim-kermany** [comment]
done
