### ISSUE TITLE
A single ConnectionSet should represent either all statefull or all non-statefull connections

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#255]
At the moment a single connection may contain stateful and non-stateful connections and a connection is considered stateful if it has at least one non-stateful connection.
Better to separate such a connection into stateful and non-stateful lines, as a result of which the connection description and potential arithmetic will be more accurate.
Follow up #199

**Comment by adisos** [comment]
Consider a separate type for `ConnectionSet` with statefulness field.  (In the reasoning there are stages where this property does not apply and is irrelevant, and the current `unknown` value is confusing).

**Comment by ShiriMoran** [comment]
structs defined in `255_stateful_revision`
PRs:
1.  Implement new structs in `VPCConnectivity`; refactor printing functionality to rely on these structs *without* actually changing and expanding the printing
2. Refactor explainability related code to use the new structs. [Anything else that relies on `VPCConnectivity` computation?] Delete old structs in `VPCConnectivity`
3. Refactor printing of `report endpoints` to be more detailed as enabled by the change - each line to contain either only stateful or only non-stateful connection
4.  [https://github.com/np-guard/vpc-network-config-analyzer/issues/529]
