### ISSUE TITLE
For explainability: accept a decription of a connection in the cli and translate it to common.ConnectionSet

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#315]
This should include defining the format of the string so that it (potentially) includes all components of a connection. 

"All connection" need not be a possible input @zivnevo @adisos

**Comment by ShiriMoran** [comment]
Some more details:
The input should contain the following details:
protocol: <string>
srcMinPort: <int>
srcMaxPort: <int>
dstMinPort: <int>
dstMaxPort: <int>

@adisos do we want to also support all the `ICMP` parms in this stage? I think we can do it later

There are few stage here:
1. Add the parms to the cli with the proper definition
2. Add validity check in the parse
3. Based on the parms create the connection with `NewConnectionSet ,AddTCPorUDPConn , AddICMPConnection` example of these can be found in e.g. `explainability_test.go`

**Comment by ShiriMoran** [comment]
E.g. for the input:
Protocol: TCP
MinSrc: 10
MaxSrc: 100
Please create a connection of protocol TCP, minSrc 10 maxSrc 100, minDst the minimal possible value, maxDst: maximal possible value (there's a const for both)

**Comment by adisos** [comment]
> After this is done we'll add another AnalysisType query and allow these parms to be specified only for this query. 

Why is the analysis type for explainability named `query`? Can rename to `explain` / `connectivity-explanation`/ anything related to explainability?
