### ISSUE TITLE
create a new type multipleVPCConfigs , to replace map[string]*vpcmodel.VPCConfig

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#317]
its first method would be getCloudName(), to be used in 
func (d *DrawioOutputFormatter) init()

**Comment by ShiriMoran** [comment]
solved by #458

**Comment by zivnevo** [comment]
Type `MultipleVPCConfigs` is now defined. Still need to add methods to it.
