### ISSUE TITLE
Enhance functionality related to pgws and fips to be oblivious to specific cidr

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#332]
A `pgws/fips` are network interface dependent, and are oblivious to the exact `cidr` of an external address.
Certain functionality, as` AllowedConnectivity(src, dst Node) *common.ConnectionSet` of `RoutingResource` requires two Nodes, which specifies specific cidr.
The relevant functionality needs to be enhanced to be oblivious to the exact cidr and be dependent only in the specific network interface and the same for all external addresses. 

(see https://github.com/np-guard/vpc-network-config-analyzer/pull/320#discussion_r1456980112)

**Comment by adisos** [comment]
will be resolved by PR #372 

Required update for explainability computation - avoid calling `getContainingConfigNode`  for the input nodes of `getRoutingResource`

**Comment by adisos** [comment]
opened small PR to update explainability code: https://github.com/np-guard/vpc-network-config-analyzer/pull/383
