### ISSUE TITLE
grouping with multi vpc

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#340]
- [ ] do not run grouping on the vpcConfig with vpcConfig.IsMultipleVPCsConfig
- [ ] do not create different resources with the same cidr/ vsis

**Comment by ShiriMoran** [comment]
> * [ ]  do not run grouping on the vpcConfig with vpcConfig.IsMultipleVPCsConfig
> 
This includes any grouping, including external addresses. Right?

>     * [ ]  do not creates different resources with the same cidr
Please refer me to a case in which resources with the same cidr are created

**Comment by haim-kermany** [comment]
I saw this happand in cases with tgw, see out_tgw_larger_example_all_vpcs__with_grouping
there are two groups with the same set of NI, and two public internet with the same cidrs

**Comment by haim-kermany** [comment]
example to make it clear:

example 1:
vsi1 and vsi2, both at the same vpc
vsi1 has connection to cidr1 and vsi2 has connection cidr2
both vsi1 and vsi2 has ca connection to cidr3 via tgw
the input that the grouping will be two vpcConfigs:
a vpc with vsi1 and vsi2, connected to cidr1 and cidr2.
v dummy vpc with  vsi1 and vsi2 both connected to cidr3.
it this example the output should be
vsi1 -> cidr1
vsi2 -> cidr2
vsi1,vsi2 -> cidr3 (via tgw)
i.e, you should do grouping in the dummy vpc and group vsi1 and vsi2 together

example 2 (same as example 1, but vsi1 and vsi2 are in different vpcs):
vsi1 and vsi2, at vpc1 and vpc2
vsi1 has connection to cidr1 and vsi2 has connection cidr2
both vsi1 and vsi2 has a connection to cidr3 via tgw
the input that the grouping will be three vpcConfigs:
a vpc1 with vsi1 , connected to cidr1 .
a vpc2 with vsi2 , connected to cidr2 .
a dummy vpc with  vsi1 and vsi2 both connected to cidr3.
it this example the output should be
vsi1 -> cidr1
vsi2 -> cidr2
vsi1 -> cidr3 (via tgw)
vsi2 -> cidr3 (via tgw)
i.e, you should not group vsi1 and vsi2 together 

example 3:
vsi1 and vsi2, at vpc1 and vpc2
vsi1 has connection to cidr1 and vsi2 has also connection cidr1
in this case, there should create only one instance of cidr1

example 4 (combination of  1 and 3):
vsi1 and vsi2, both at the same vpc
vsi1 has connection to cidr1 and vsi2 has also connection cidr1
both vsi1 and vsi2 has ca connection to cidr3 via tgw
the input that the grouping will be two vpcConfigs:
a vpc with vsi1 and vsi2, connected to cidr1.
a dummy vpc with  vsi1 and vsi2 both connected to cidr3.
it this example the output should be
vsi1,vsi2 -> cidr1
vsi1,vsi2 -> cidr3 (via tgw)
in this case, you should create only one instance of endpoint element with vsi1,vsi2

**Comment by ShiriMoran** [comment]
**Summarizing**
The following rules should be kept in grouping:
* group vsis of the same vpc when feasible
* group external addresses when feasible
* do not group vsis that are not in the same VPC, even if they have the exact same connections

@haim-kermany please approved
impl details:
a dummy VPC is generated for each tgw; the dummy vpc contains the tgw and the resources it connects @adisos @haim-kermany please approve

@adisos Can we have two vsis of the same VPC that connects to the same external address through two different tgw?

**Comment by haim-kermany** [comment]
1. it also relevant for subnets, not only vsis
2. I whould also add:
when a subset of vsis/externalAddresses/subnets are grouped twice at two different VpcConfigs, create only one instance of endpointElement, and use this endpointElement in both VpcConfigs
(see example 3,4)

**Comment by adisos** [comment]
Comment about the examples: there are no connections to external cidrs from vsis through tgw.. only internal connections are through tgw resources.

**Comment by adisos** [comment]
> Can we have two vsis of the same VPC that connects to the same external address through two different tgw

there is no connection to external address through tgw

**Comment by adisos** [comment]
This is a multi-vcpc analysis issue, where grouped elements should be available for all vpcs, not only per vpc. (to avoid identical grouped elements created in different objects, in two different vpc analysis results).

**Comment by ShiriMoran** [comment]
> This is a multi-vcpc analysis issue, where grouped elements should be available for all vpcs, not only per vpc. (to avoid identical grouped elements created in different objects, in two different vpc analysis results).

This is clear

**Comment by ShiriMoran** [comment]
Grouping implementation enhancements:
The grouping, as other computations, is performed separately for each `VPC`
1.  If  `vpcConfig.IsMultipleVPCsConfig` is high then group `vsis/subnets` only if they originate in the same `VPC`. This will effect all formats
2. There should be a single copy of each grouped `vsis/subnets/IPs ` across all `VPCs`. This can be achieved either by keeping a "global" list of all grouped elements or by merging grouped elements after the analysis stage is completed.

@adisos @haim-kermany please approve
@haim-kermany did you see an example of 1 - namely, two `vsis` not from the same `VPC` that are grouped in a dummy `VPC`?

**Comment by haim-kermany** [comment]
1. + 2. yes, it seems correct
see out_tgw_larger_example_all_vpcs__with_grouping

**Comment by ShiriMoran** [comment]
Once I solve #409 there will be examples for 1 above in `input_tgw_basic_example_multiple_regions.json`

**Comment by zivnevo** [comment]
> Grouping implementation enhancements: The grouping, as other computations, is performed separately for each `VPC`
> 
>     1. If  `vpcConfig.IsMultipleVPCsConfig` is true then group `vsis/subnets` only if they originate in the same `VPC`. This will effect all formats
> 
>     2. There should be a single copy of each grouped `vsis/subnets/IPs ` across all `VPCs`. This can be achieved either by keeping a "global" list of all grouped elements or by merging grouped elements after the analysis stage is completed. This will effect only drawio
> 
> 
> @adisos @haim-kermany please approve @haim-kermany did you see an example of 1 - namely, two `vsis` not from the same `VPC` that are grouped in a dummy `VPC` grouping?
> 
> @zivnevo architecture question: which of the options in 2 seems better

I would go for the second approach (unifying isomorphic groups as a post-processing stage)

**Comment by zivnevo** [comment]
@ShiriMoran , @haim-kermany , can we close this issue?

**Comment by haim-kermany** [comment]
yes
