### ISSUE TITLE
Explainability: Consistent handling of partialy specified connection

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#343]
The current implementation to specified connection assumes no degree of freedom.  Namely:
1. The answer to the query is that the connection exists only if the entire connection exists
1. Any port not specified assumes the relevant min/max value
Thus, if one queries for a `TCP` connection without specifying ports and `TCP` connection exists only on port 56 then the answer will be that the connection is blocked.
Actually, this is not very consistent since if no connection is specified then the query looks for "any connection between source and destination", but if the protocol is specified ports are not specified then the query looks for "all ports must be in the connection".

Perhaps the smooth way to handle this is via enhancing the connection package (otherwise it could become very messy, as specified ports and unspecified ports should be treated differently)

**Comment by adisos** [comment]
what kind of enhancement do you suggest and to which exact package (did you mean 'common`?)

**Comment by ShiriMoran** [comment]
Enhance `ConnectionSet` in `common`.
The idea is to enable a "don't care" in connection's ports and enhance the operators accordingly. However, this is very initial and still needs to be finalized and see if feasible.
The first step needs to be defining the exact spec. Even this is not completely trivial. 
Intuitively, unspecified ports should be treated as don't cares.

**Comment by ShiriMoran** [comment]
The consistency is maintained by checking for intersection with the queried connection instead of containment. Solved by PR https://github.com/np-guard/vpc-network-config-analyzer/pull/351
