### ISSUE TITLE
Investigate an ignored error of *nacl 

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#344]
In:
`func (n *NACL) AllowedConnectivity(src, dst vpcmodel.Node, isIngress bool)`
error returned from `common.IsAddressInSubnet` is ignore.
Trying not to ignore the error results in many tests failing.
This has to be investigated and fixed

**Comment by adisos** [comment]
The issue was that `common.IsAddressInSubnet` handled only IP Address, but was called also for external nodes with CIDR instead of IP Address (though should not have been called for external nodes at all). 
Fixed in PR #394 .

**Comment by ShiriMoran** [comment]
`The` reason ignoring the error did not cause any errors was that the ignores case were not in any `subnet` and so were treated correctly.
