### ISSUE TITLE
explainability enhancements

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#368]
currently not supported:

- [ ]  iks nodes : the fix for associating SGs with relenvat IKS nodes was added - now it is left to avoid blocking explainability with iks nodes, and add the tests from the relevant kept branch. 

- [ ] transit gateways : WIP 

- [ ] should subnets analysis also support explainability?

@ShiriMoran please check and add other known limitations

e.g. what about VPE and its reserved IPs?

**Comment by ShiriMoran** [comment]
First two items are part of V0.4
Third one is not part of a planned release, at the moment

**Comment by ShiriMoran** [comment]
first two items already in back in V0.4
last one has a separate issue #539 

Can this issue be closed? @adisos
