### ISSUE TITLE
A flag to output resource model

### ISSUE THREAD

**Issue by zivnevo** [np-guard/vpc-network-config-analyzer#404]
Collecting resources directly from the account takes time, but user may want to run multiple queries on the collected resources.
It therefore makes sense to collect the resources on the first query, then save the resource model for future queries.
Suggesting to add a new flag `-dump-resources` which takes a file name, and Marshals the resource model into this file.

**Comment by olasaadi99** [comment]
do you want for this flag to also analyze this config or just marshal it?

**Comment by zivnevo** [comment]
The analyzer always analyzes 😺 
If I just wanted to marshal, I would run the collector instead.
