### ISSUE TITLE
Grouping should not be based on names - switch to UID()

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#412]
Theoretically basing grouping on names was always a bad idea, as names are not unique.
Practically, it is especially a bad idea in the context of multi vpcs.

**Comment by adisos** [comment]
>  as names are not unique.

The names of network interfaces in the model consists of vsi name + ip address, so it is less likely to have multiple identical names across different VPCs. 

Still, better change to `UID`.

**Comment by ShiriMoran** [comment]
> > as names are not unique.
> 
> The names of network interfaces in the model consists of vsi name + ip address, so it is less likely to have multiple identical names across different VPCs.
> 
> Still, better change to `UID`.

1. Once we support multiple vpc with same addresses prefix space it will be more likely
2. In subnet analysis mode the keys are subnets names. Not sure how likely it is that subnets across VPC will share names (probably it is not likely for subnets of the same VPC to share names). But it is possible

Having said that, I'm fine with giving this low priority @zivnevo @adisos

**Comment by ShiriMoran** [comment]
solved by https://github.com/np-guard/vpc-network-config-analyzer/pull/461
