### ISSUE TITLE
drawio: all connection arrows should be black

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-analyzer#415]
In some cases connectivity arrows appear to be blue.

**Comment by zivnevo** [comment]
![two_regions drawio](https://github.com/np-guard/vpc-network-config-analyzer/assets/79099626/a8120f12-4979-4272-b8b7-3271068f6508)

**Comment by haim-kermany** [comment]
@kyorav can you please specify when to use blue line?

**Comment by kyorav** [comment]
Blue lines show "attachment" relationship, when a single resource is composed of multiple parts (represented by multiple icons) the blue lines connect the various parts (without an arrow):
- A VPE (Endpoint Gateway) may have multiple RIPs
- A VSI may have multiple NIFs attached
- A Transit Gateway is connected to multiple VPCs
- A Load Balancer pool includes multiple members
- A Public Gateway may be attached to several subnets

**Comment by haim-kermany** [comment]
![image](https://github.com/np-guard/vpc-network-config-analyzer/assets/82028281/26750488-7b4f-434a-a4bf-6890f6e8b4c9)
the blue represent "public"
dash represent "logical"
see picture
the list you wrote is "logical"

**Comment by kyorav** [comment]
I think the things on my list should be "logical links" and the connectivity map should use "unidirectional connections" between source and destination. I think it would be easier to parse if logical links were blue, but not a hill to die on. While we are at it, I also prefer to see bi-directional connections represented as black lines with arrows on both sides, and not the "connection" from the template. 
@zivnevo , @adisos -- what do you think?

**Comment by haim-kermany** [comment]
I think we need to use only lines from the list of the ibm connectors (the lines in the list)
please notice that
1. dashed blue is not on this list
2. line with two errows is not no the list.

**Comment by kyorav** [comment]
This template was designed only for architecture diagrams and does not include mechanisms to display connectivity maps or anything else. The connectors in the template that refer to "connections" are not meant to represent "allowed connectivity", they have a different meaning. Yes, when we draw things that are modeled in the template we should use the correct style from the template. But when we are drawing things that are outside the scope of the template we can use whatever makes the drawing better.

**Comment by haim-kermany** [comment]
NP,
in practice each line can be:
blue/black
dashed/not dashed.
each end can be arrow/little point/ nothing

**Comment by zivnevo** [comment]
I suggest the following:
* **Traffic is allowed from A to B** - black line with a dot on A and an arrow on B
* **Same kind of traffic is allowed from A to B and from B to A** - black line with arrows on both A and B
* **A is attached to B** - blue line, no arrows (maybe dots?)

**Comment by haim-kermany** [comment]
fixed
