### ISSUE TITLE
unit testing for grouping unification 

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#429]
The practical effect of this unification is only in `drawio`  - the fixes originated in Haim's request. Its more natural to test it there. I can only test, or try to test, cumbersome side effects of the unification, and not sure the test can be decoupled from the actual impl (and as such problematic). 
Perhaps we can open an issue for this and see what it the best way to test it.

_Originally posted by @ShiriMoran in https://github.com/np-guard/vpc-network-config-analyzer/pull/423#discussion_r1506260364_
            
The unification process is so that in the drawio presentation each semantic group is presented only once; this includes groups that are both `src` in a line and `dst` in another line in the single vpc context or e.g. the same external IP groups in the multi VPC context. 
Not sure what is the best way to smoothly test this in unit test. Better avoid messy pointer comparison.

**Comment by adisos** [comment]
I think it may be sufficient to add mechanism to identify cache hits, and then have two examples in unit tests that demonstrate the caching and verify those cache hits. The examples are required for both flows - one for grouping  for multi-vpc level, and one for grouping after self-loop grouping runs, within single vpc context.
