### ISSUE TITLE
Analyze IKS nodes with SG correctly 

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#443]
see https://github.com/np-guard/vpc-network-config-analyzer/pull/441#discussion_r1518884832 

IKS automatically apply two SGs to all worker nodes:

    - the VPC's default SG (you can find it in the config object, under the VPC config)
    - a security group that they generate, which is called "kube-<cluster-ID>"

I think we should do the analysis with both of those.

It is possible for the user to request additional SGs at creation time, which we wouldn't know about, which makes our analysis an under approximation. We can add a warning message that mentions that.

- [x] cluster ID should be added to the config object 
- [x] generation of VPCConfig should associate the relevant SGs to the IKS nodes 

collector updates:
list of clusters, and list of nodes per cluster ("Workers")

**Comment by olasaadi99** [comment]
https://github.com/np-guard/cloud-resource-collector/pull/212
