### ISSUE TITLE
drawio ignors pgw in grouping mode

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#445]
see example from ziv

**Comment by haim-kermany** [comment]
@zivnevo
@kyorav 
@adisos 


hi all
in example iks_workers_large, we have the following grouped connectivity:
vsi1,vsi2 -> "Public Internet"

both vsi1 and vsi2 have a floating IP.
so, what sould I do with the FIP? ignore both of them? ungroup  the connection?

**Comment by kyorav** [comment]
I am not sure there is a "right answer" here, but my feeling is that routing information is less important than readability, so I vote for ignoring the FIPs.

**Comment by haim-kermany** [comment]
@kyorav , but still draw the fip icon. right?
