### ISSUE TITLE
can now check address prefixes of the vpc instead of subnets

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#467]
can now check address prefixes of the vpc instead of subnets

_Originally posted by @adisos in https://github.com/np-guard/vpc-network-config-analyzer/pull/458#discussion_r1528677395_

**Comment by ShiriMoran** [comment]
I'm not sure this has to be done -  I think the current error messages that refers to subnets is good enough

**Comment by ShiriMoran** [comment]
@zivnevo I think this should not be part of V0.4

**Comment by zivnevo** [comment]
I cannot understand what this issue is about from its title + description, so I cannot decide if it should be part of 0.4 or not.
@adisos , if you understand the context, please set the milestone.

**Comment by ShiriMoran** [comment]
This is about the error messages delivered in explainability. The question was whether to check, for a given vsi address as src/dst, if its inside the subnet's address range or the VPC's address prefix.
Anyways, I've just noticed this was already solved - I'll just update the relevant error messages and submit a PR. So we can keep in in V0.4

**Comment by ShiriMoran** [comment]
Turns out there are config objects that are missing the input address prefixes. ROI of having a WA for this not worth it. We'll stay with the subnets range for now.
