### ISSUE TITLE
handle load balancer 

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#469]
from the parser to the output

**Comment by haim-kermany** [comment]
- [ ] handle rules policies
- [ ] format and report linting messages
- [ ] support non abstraction mode
- [ ] support explainability
- [ ] support multi  explainability

**Comment by adisos** [comment]
```
user -> ip
ip -> backend 
```

in both segments, check if connectivity is separated by one of the PIPs , if yes - at least mark with ** 

` ** this connectivity does not cover all endpoints (more details in linting )`


add debug mode with private IPs in the connectivity report

**Comment by haim-kermany** [comment]
**check non trivial SG example (add test) -**  both iks_workers_large and iks_config_obj has SG on LB.

**Comment by haim-kermany** [comment]
> > **check non trivial SG example (add test) -** both iks_workers_large and iks_config_obj has SG on LB. after implementing non abstraction mode, it will be easier to review
> 
> can you provide more details? are those non-trivial SG? why is it difficult to see their impact on connectivity results with current LB abstraction?

the SGs are applied on the pips. and the LB abstraction remove the pips and their connectivity, so it is hard to see the impact of the SGs on the connectivity

**Comment by adisos** [comment]
> > > **check non trivial SG example (add test) -** both iks_workers_large and iks_config_obj has SG on LB. after implementing non abstraction mode, it will be easier to review
> > 
> > 
> > can you provide more details? are those non-trivial SG? why is it difficult to see their impact on connectivity results with current LB abstraction?
> 
> the SGs are applied on the pips. and the LB abstraction remove the pips and their connectivity, so it is hard to see the impact of the SGs on the connectivity

but it should have impact on the connectivity of the LB itself..

**Comment by haim-kermany** [comment]
> > > > **check non trivial SG example (add test) -** both iks_workers_large and iks_config_obj has SG on LB. after implementing non abstraction mode, it will be easier to review
> > > 
> > > 
> > > can you provide more details? are those non-trivial SG? why is it difficult to see their impact on connectivity results with current LB abstraction?
> > 
> > 
> > the SGs are applied on the pips. and the LB abstraction remove the pips and their connectivity, so it is hard to see the impact of the SGs on the connectivity
> 
> but it should have impact on the connectivity of the LB itself..

it should, but not all the time, and it is hard to investigate it without seeing the pip connectivity report

**Comment by adisos** [comment]
> > > > > **check non trivial SG example (add test) -** both iks_workers_large and iks_config_obj has SG on LB. after implementing non abstraction mode, it will be easier to review
> > > > 
> > > > 
> > > > can you provide more details? are those non-trivial SG? why is it difficult to see their impact on connectivity results with current LB abstraction?
> > > 
> > > 
> > > the SGs are applied on the pips. and the LB abstraction remove the pips and their connectivity, so it is hard to see the impact of the SGs on the connectivity
> > 
> > 
> > but it should have impact on the connectivity of the LB itself..
> 
> it should, but not all the time, and it is hard to investigate it without seeing the pip connectivity report

not all the time -- because the connectivity is not consistent for all pips? 
I think we should have a basic example where it is consistent for all pips, and reflected clearly in the report for the abstracted LB connectivity.

**Comment by haim-kermany** [comment]
lets take it online

**Comment by haim-kermany** [comment]
iks_config_object has a SG that reflect the LB connectivity 
I added a test to the branch "non-lb-abstraction-mode". there was already a test for abstract mode

**Comment by zivnevo** [comment]
Done
