### ISSUE TITLE
explainability for all pairs of EndpointElem

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#471]
for html, we need a query that creates an explanation for all pairs of EndpointElem

**Comment by ShiriMoran** [comment]
Interface: 
The relevant function will get as input all couples of `EndPoints` for which explainability query is required, and will return an `Explanation` struct for each such couple. Namely, the input will be a slice of couples of `Endpoints` and the output will be a slice of `Explanation`.
Comments:
1. In the input, each Endpoint can be either an VSI or grouped external address. Specifically, we do not support (at the moment) grouped VSIs or Subnets 
2. Some minor manipulation on the `Explanation` output might be required for the actual output string. If needed we will add functionality - such as avoiding certain headers w.r.t. the standard text or debug output.

**Comment by ShiriMoran** [comment]
resolved by PR #536
