### ISSUE TITLE
HTML output - visualization, comments, bugs

### ISSUE THREAD

**Issue by zivnevo** [np-guard/vpc-network-config-analyzer#516]
1. graph title should not be "NCA Graph" Change to something like "VPC Connectivity Diagram"
2. https://github.com/np-guard/vpc-network-config-analyzer/issues/360
3.

**Comment by haim-kermany** [comment]
Hi @zivnevo @kyorav @adisos 
HTML output is now supported.
please try it, and comment here whatever you thing will improve it
tnx

**Comment by zivnevo** [comment]
Not only it is supported, it was already demoed to clients today 😃 That's how this issue was born.
Hopefully, clients will play with it (we made a pre-release version for that) and provide more feedback.
