### ISSUE TITLE
Support SG rules with new "Local" field

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#519]
- [x] #523
- [x] #525
- [x] #527

![image](https://github.com/np-guard/vpc-network-config-analyzer/assets/82078442/34e7bd12-a786-4566-ae04-12a883f7aa8a)

![image](https://github.com/np-guard/vpc-network-config-analyzer/assets/82078442/337a67fe-084e-4924-9305-e7112aaa8100)

**Comment by zivnevo** [comment]
Can closed as well?
