### ISSUE TITLE
hierarchical help menu

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-analyzer#537]
The help message you get when running `vpcanalyzer -help` is too long to fit in a single screen, and related information is spread all over the place. It would be nice to have a heirarchical help menu, so I could get help about each mode of operation separately (all-endpoints, all-subnets, explain, html-output)

**Comment by zivnevo** [comment]
We should consider abandoning [flag](https://pkg.go.dev/flag@go1.22.2) in favor of [cobra](https://pkg.go.dev/github.com/spf13/cobra).
Then we can define sub-commands. each with its own set of settings. An initial suggestion:
* `vpcanalyzer report` - connectivity reports (both textual and graphical)
* `vpcanalyzer explain` - explaining connectivity from src to dst
* `vpcanalyzer version` - prints the version

In the future:
* `vpcanalyzer lint` - run lint checks
* `vpcanalyzer verify` - check whether a given set of connections are allowed/denied

@adisos
