### ISSUE TITLE
getLocalCidr returns empty result. could not convert localObj to expected type 

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#549]
with the load balancer examples that @kyorav  created, I get the following error in the main branch:
" getLocalCidr returns empty result. could not convert localObj to expected type "
the errors happened during the parsing 
these errors started to show in the last few days, and I think they are related to @olasaadi99 PR:
https://github.com/np-guard/vpc-network-config-analyzer/pull/530
I created a branch with the examples:
https://github.com/np-guard/vpc-network-config-analyzer/tree/sg_analysis_with_lb

@zivnevo @adisos, I would consider adding this issue to 0.4, its looks that every config of a load balancer with SG will issue this error

**Comment by olasaadi99** [comment]
Hi
yes this is related to my pr, there is no bug, you just need to add a new required field that was added by https://github.com/np-guard/cloud-resource-collector/pull/194
just add
 `"remote": {
                        "cidr_block": "0.0.0.0/0"
                    },`
 in security_groups -> rules

**Comment by haim-kermany** [comment]
> "local": { "cidr_block": "0.0.0.0/0" },

should it be the first or the last?

**Comment by zivnevo** [comment]
@olasaadi99 , can we maintain backwards compatibility somehow? That is, will it be safe to set `local` to `0.0.0.0/0` if it is not present?

**Comment by olasaadi99** [comment]
> > "local": { "cidr_block": "0.0.0.0/0" },
> 
> should it be the first or the last?

did not understand.. I pushed the commit to your branch

**Comment by olasaadi99** [comment]
> @olasaadi99 , can we maintain backwards compatibility somehow? That is, will it be safe to set `local` to `0.0.0.0/0` if it is not present?

it must be present, it is a required filed, it is in the collector's output with the new version, and I have updated all of the config files

**Comment by zivnevo** [comment]
no fix needed

**Comment by haim-kermany** [comment]
@olasaadi99 tnx, works for me
