### ISSUE TITLE
handle LB adresses arbitrariness 

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#560]
1. when LB created, the address of the private IPs are chosen arbitrarly, which can affect connectivity results
2. when creating dummy Private IPs, we choose a free address - that can affect the result
3. choosing an address for the dummy public IP can also effect the result

**Comment by haim-kermany** [comment]
shiri words:


If the relevant filtering rules (SG, NACL, ...) are not unified w.r.t. the subnet's cidr then different pIP of the same subnet may result in different connectivity results.
This is something we should address (not in this PR).

    By issuing a warning - consider a linter?
    By ignoring the allocated pIP and provide maximal potential (and also minimal?) connectivity - note that the maximal potential connectivity may never be realized for an instance of the load leveler.

**Comment by adisos** [comment]
check all VPCs SG And NACL , if none is separating this subnet - no issue.
if yes - choose PiP for each segment in the subnet.
(though separating a subnet connectivity is bad practice and not supported by connectivity analysis)

**Comment by adisos** [comment]
- the LB analysis should fail if SG rule splits a subnet (associated with the LB)
- add linting for this case

**Comment by haim-kermany** [comment]
both SG and NACL can split the subnet CIDR.
if a subnet cidr is splited to more than one block, we need to  create a private IP per block, not per subnet.
also warn, and lint

**Comment by adisos** [comment]
@haim-kermany can this issue be closed now?

**Comment by haim-kermany** [comment]
> @haim-kermany can this issue be closed now?

is there still a lint case here? or the general "filter split subnet" lint cover it?

**Comment by zivnevo** [comment]
@ShiriMoran has already implemented the "nACL should not split a subnet" check.
It's OK in general for SG to split subnets, unless this may affect LB connectivity.
There is an additional check planned for this - see #116 (4).

**Comment by haim-kermany** [comment]
tnx, so this one can be closed
