### ISSUE TITLE
Reserved IPs in a subnet

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#566]
To summarize: 
the documentation says "`// all the allocated IPs are at subnetObj.ReservedIps. (did not find documentation, it is what we experiment)`" @kyorav @haim-kermany @adisos is that safe? are we OK with this? 
To be on the safe side, I'm opening an issue in which we can discuss and document the discussion

1. All the IPs which are being used will be listed as reserved IPs. Is this a valid assumption?
2. An IP not allocated is free and can be used? I think I recall there are IPs which are always reserved for IBM usage 

@kyorav @adisos

**Comment by kyorav** [comment]
1. All the IPs that are used by the LB _at the time the collector was invoked_ will appear in the `reserved_ips` field of one of the subnets and also in the "private_ips" field of the load-balancer. However, at runtime the LB can scale out and add more IPs. It will choose additional IPs from the list of subnets attached to it.
2. Correct. The IPs reserved by IBM appear in the `reserved_ips` field for all subnets (always the first 4 addresses + the last address). Other IPs that are already in use will also appear as reserved IPs, e.g. the addresses of network interfaces of VSIs.
