### ISSUE TITLE
In explainability - allow any cidr of internal addresses

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#576]
As per @kyorav the input validity test that the `cidr` is contained in a single `VPC` should be removed.
It suffice to check that the `cidr` is either external or internal and for an internal `cidr` that it contains at least one endpoint (which we already do).

The reason this input validity test has to be removed is that in many cases the address prefixes we want to query about do not add up to a single `cidr`; the `cidr` containing them will also includes other internal addresses, usually unused.

When solving this issue tests of multiple rules in a single transit connection for an explanation query can and should be added.

@kyorav @adisos 
what release do you want it in @zivnevo? (V0.5 should be possible if this is what you want)

**Comment by zivnevo** [comment]
> As per @kyorav the input validity test that the `cidr` is contained in a single `VPC` should be removed. It suffice to check that the `cidr` is either external or internal and for an internal `cidr` that it contains at least one endpoint (which we already do).
> 
> The reason this input validity test has to be removed is that in many cases the address prefixes we want to query about do not add up to a single `cidr`; the `cidr` containing them will also includes other internal addresses, usually unused.
> 
> When solving this issue tests of multiple rules in a single transit connection for an explanation query can and should be added.
> 
> @kyorav @adisos what release do you want it in @zivnevo? (V0.5 should be possible if this is what you want)

V0.5 would be nice. Can also wait for v0.6

**Comment by ShiriMoran** [comment]
> 
> V0.5 would be nice. Can also wait for v0.6
Fine. I'll do it now, thus saving the context switch time

**Comment by ShiriMoran** [comment]
I'm working on it as part of PR #574 (so that we can check "multiple prefixes single connection")

Not supported (at least for now):
1. `src`, `dst` of different `VPC`s connected by more than one `tgw`
2. `src/dst` is an internal address that has `VSI`s in more than one `VPC`

@kyorav @adisos @zivnevo fyi (any objections? )
