### ISSUE TITLE
use only debug switch, remove debug output format 

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#592]
- the output given as "debug output format" should be provided with `-debug` switch from cli, as it gives a more detailed output.
more formats will have the option to use the debug switch (not only text). 
- the more detailed logs should be printed with `-verbose` switch, instead of `-debug`
- consider a new flag for more detailed explanation in explainability

**Comment by adisos** [comment]
after this update, the LB analysis without abstraction with be associated with `-debug` instead of the "debug output format" , and will be supported in all formats (not only text)

**Comment by haim-kermany** [comment]
after discussion, desided to:
1.  remove the debug cli switch
2. revisit the debug output format
3. revisit the initiation of detailed explainability
4. revisit the initiation of load balancer Abstraction

**Comment by haim-kermany** [comment]
recommendation after talking with @ShiriMoran :
1. sunset debug output format
2. add detailedExplain flag - effect both html and text. default is true, hidden
@zivnevo,  @adisos, please comment

**Comment by zivnevo** [comment]
I think it's OK to add a regular flag, if it only applies to `vpcanalyzer explain`. No need to hide it.
Options to name this flag: `--minimal`, `--consice`, `--short` or `--summary`

**Comment by haim-kermany** [comment]
the flag should also effect html output, so its can not be under explain

**Comment by ShiriMoran** [comment]
Regarding DEBUG output format for connectivity reports - now that the TCP responds info is provided always and that we have the explainabilty, I don't see the use case for these reports. We can remove them, I believe.
