### ISSUE TITLE
non needed html test result files generated

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#594]
`TestAllWithGeneration` func of  `analysis_output_test.go` generates `html` files which are not required for the testing. 
fyi @adisos

**Comment by haim-kermany** [comment]
fixed here:
https://github.com/np-guard/vpc-network-config-analyzer/pull/598

**Comment by adisos** [comment]
a better approach is to avoid generation rather than adding to `gitignore`
there is already mechanism to avoid generation of drawoi, can be also used for the html files
