### ISSUE TITLE
seg fault on nacl example

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#608]
see branch `nacl-split-subnet-segfault`
test:
	{
		inputConfig: "nacl_split_subnet",
		useCases:    []vpcmodel.OutputUseCase{vpcmodel.AllSubnets},
		format:      vpcmodel.Text,
		grouping: true,
	},

**Comment by adisos** [comment]
Missed a check that connectivity implied by the "remote" part of ACL rule remains within subnets resolution, and does not split subnets.
