### ISSUE TITLE
TGW analysis  - consider TCP response for connectivity based on prefix filters in endpoints report

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#613]
In our current impl it is assumed it is - and this has to be verified
@kyorav

**Comment by kyorav** [comment]
A transit gateway is not a "firewall" type of device, so it is neither statefull nor stateless. It does not permit or deny connections, it just routes packets. It determines whether an address exists on the network or not.
Where does the statefull assumption come into play? What we need to verify is the behavior of our analysis.

**Comment by adisos** [comment]
If the TGW prefix filters block the response for TCP connection, this should be reflected in the connectivity analysis.
