### ISSUE TITLE
When all connections are allowed but response is denied, two connections now appear in diagrams, instead of one.

### ISSUE THREAD

**Issue by zivnevo** [np-guard/vpc-network-config-analyzer#738]
We now have one connection with the label `ICMP, UDP`, and another connection with the label `TCP *`.
Sometimes these two connections appear one on top of the other, and the labels are hard to read.
We should have in the diagrams only one connection.

![image](https://github.com/user-attachments/assets/ac7df1e2-24dd-4056-952a-199c7d947b78)
![image](https://github.com/user-attachments/assets/30b8803e-acf0-4a91-832d-b250f8fc125b)

**Comment by haim-kermany** [comment]
we do have two lines in the text report.
do we want one edge to represent two lines?

**Comment by zivnevo** [comment]
yes!
