### ISSUE TITLE
check aws explainabiliy

### ISSUE THREAD

**Issue by haim-kermany** [np-guard/vpc-network-config-analyzer#756]
after nacl is supported, explainability should work.
additional support is needed for public/private subnets

- [x] support public subnets
- [x] detailed explain of public subnets
- [x] adding test infrastructure for aws explainability
- [x] check correctness of examples  + adding interesting tests (html is a great platform for it)

**Comment by ShiriMoran** [comment]
add examples:
1. Private subnet s.t. the path in/to external is being blocked in the subnet
2. Private subnet blocking  both in egress and ingress
3. Public subnets enabling connection to the internet
