### ISSUE TITLE
Explain: correctly handle case of two SGs of which only one enables the connection

### ISSUE THREAD

**Issue by zivnevo** [np-guard/vpc-network-config-analyzer#759]
I have an example (cannot be attached here) where I see the following inconsistencies when looking at the HTML explanation for two **IKS** endpoints with "All connections" allowed.

- [ ]  Path contains a '|' right after the source endpoint, but then continues to the next elements
- [ ]  Path shows an SG that doesn't allow the connection, instead of the SG that does allow it
- [ ]  In the path, instead of seeing the name of the NACL at ingress, the subnet name is printed
- [ ]  In the Details section, the first Egress item is `security group foo blocks connection since there are no relevant allow rules`, but the connection is allowed, so users may find it confusing.

**Comment by ShiriMoran** [comment]
Not sure I follow - is it a single case between two IKS endpoints with all these issues, or several?
Can you open a branch with the relevant example, and mention the relevant endpoints?

**Comment by ShiriMoran** [comment]
I managed to reproduce it. 
* 

> I have an example (cannot be attached here) where I see the following inconsistencies when looking at the HTML explanation for two **IKS** endpoints with "All connections" allowed.
> 
>     * [ ]   Path contains a '|' right after the source endpoint, but then continues to the next elements
Indeed
> 
>     * [ ]   Path shows an SG that doesn't allow the connection, instead of the SG that does allow it
Could it be that both are relevant?
> 
>     * [ ]   In the path, instead of seeing the name of the NACL at ingress, the subnet name is printed
What I see is that the NACL is printed as well as the subnet name, as it should be.
Anyways, the subnet name should be printed.
> 
>     * [ ]   In the Details section, the first Egress item is `security group foo blocks connection since there are no relevant allow rules`, but the connection is allowed, so users may find it confusing.

At first sight it seems to me that there are two SGs connected to it, or at least this is what is being identified. One allows connection and the other disallows. The source of the bug seems to be that explainability identified the SG as blocking while the analysis identifies the connection as existing

**Comment by ShiriMoran** [comment]
I fixed the path bug. I think that in the details, instead of 
"Security Group xxxx blocks connection since there are no relevant allow rules"
I'll print
"Security Group xxxx does not allow connection since there are no relevant allow rules" (in all cases)
For other filters/routers no change

**Comment by zivnevo** [comment]
Maybe it is enough to just have
"Security Group xxxx has no relevant allow rules"

**Comment by ShiriMoran** [comment]
solved by https://github.com/np-guard/vpc-network-config-analyzer/pull/768
