### ISSUE TITLE
Refactor testcase so that there is a basic struct and seperate struct for each report, diff, explain and lint

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#765]
It would make much more sense if each subcommand will extend a basic Testcase struct with its own required fields.
Currently this struct is a mess, as it serves report, diff, explain and lint

_Originally posted by @zivnevo in https://github.com/np-guard/vpc-network-config-analyzer/pull/764#discussion_r1709010144_

**Comment by haim-kermany** [comment]
please notice that a vpcGeneralTest struct was duplicated into aws package
