### ISSUE TITLE
TCP response from LB is blocked, but it is unclear why

### ISSUE THREAD

**Issue by zivnevo** [np-guard/vpc-network-config-analyzer#776]
In the connectivity report I see
```
iks-node[10.241.0.29] => kube-33[LoadBalancer] : protocol: TCP *
```

But running `vpcanalyzer explain` doesn't provide good reasons for this.
When the LB's private IP is in the same subnet, I don't get an explanation at all for the blocked return path (because there can't be one).
When the LB's private IP is in another subnet, I get an explanation why the response is **allowed**.
```
TCP response is disabled; The relevant rules are:
	Egress:
		network ACL my-acl allows connection with the following allow rules
			index: 1, direction: outbound , src: 0.0.0.0/0 , dst: 0.0.0.0/0, conn: all, action: allow

	Ingress:
		network my-acl allows connection with the following allow rules
			index: 0, direction: inbound , src: 0.0.0.0/0 , dst: 0.0.0.0/0, conn: all, action: allow
```

**Comment by zivnevo** [comment]
This seems like a more general issue with LB connectivity.
Connectivity shows `TCP*` for two NI in the same subnet, which doesn't make sense.

```
iks-node[10.241.0.29] => kube-33[LB private IP][10.241.0.5] : protocol: TCP *
```

**Comment by haim-kermany** [comment]
got the same bug at out_load_balancer_all_vpcs__with_grouping_no_lbAbstract.html
