### ISSUE TITLE
fix string returned for NACL rule in AWS

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#807]
1.The string describing rules in aws NACL  contains `conn: -1` which should be fixed.
This occurs for rules with the following (which stands for "all connections" ?)
                    ```" IcmpTypeCode": null,
                    "Ipv6CidrBlock": null,
                    "PortRange": null,
                    "Protocol": "-1",```
1. The string does not contain `"RuleNumber" ` which is the priority of the rule and thus is crucial 
(I wonder how are ties broken for rules with the same RuleNumber and how is consistency guranteed @kyorav )
1. Instead of the title CIDR - or in addition to it - we should add src/dst for ingress/egress as described in [here](https://docs.aws.amazon.com/vpc/latest/userguide/nacl-rules.html)

Examples can be seen in `vpc-network-config-analyzer\pkg\awsvpc\examples\out\explain_out\ip_to_ip_all_vpcs_explain_detail.txt`

**Comment by kyorav** [comment]
The API does not allow creating multiple nACL rules with the same rule number (priority).

**Comment by ShiriMoran** [comment]
> The API does not allow creating multiple nACL rules with the same rule number (priority).

But e.g in [this example](https://github.com/np-guard/vpc-network-config-analyzer/blob/main/pkg/awsvpc/examples/input/input_aws_sg_1.json#L888) there are multiple rules with the same priortity
![image](https://github.com/user-attachments/assets/16a88566-8cba-4e05-bd0e-3840f0f20b77)

**Comment by kyorav** [comment]
Ingress and Egress are evaluated separately. There will never be two rules in the same ACL with the same rule number and the same value for `"Egress"`.

**Comment by haim-kermany** [comment]
is this done?

**Comment by ShiriMoran** [comment]
apart from the last item, all is solved by https://github.com/np-guard/vpc-network-config-analyzer/pull/826/files
If we decide to change the format as in the last item here -  so that it will look like the GUI -  we will do it in another issue
