### ISSUE TITLE
fix string returned for SG rules in aws

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#808]
The returned string "index" should be replaced by "index in egress list" or "index in ingress list" so that it will indeed describe the rule as provided; otherwise it is inconsistent with the actual input and is confusing. Of course, the index should be the correct one w.r.t. the relevant list. At the moment the provided index seems to be of an imaginary concatenation of the two lists (ingress and egress).

**Comment by haim-kermany** [comment]
@ShiriMoran is this done?

**Comment by ShiriMoran** [comment]
solved by https://github.com/np-guard/vpc-network-config-analyzer/pull/826
