### ISSUE TITLE
AWS IDs in output

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-analyzer#814]
If there is a name for a resource (a tag with key "Name") then all outputs should use the name and not the ID. Internally, the ID needs to be the unique identifier of a resource because the name might not exist or not be unique, but the users don't want to see it if they don't have to.

Specifically for NIFs, if an instance has only one NIF, then we should use the instance name to identify that endpoint in the output.

I think the above holds for all output formats except for JSON.

**Comment by olasaadi99** [comment]
for nif in both aws and ibm we do use name of instance in the output (with brackets and address)
