### ISSUE TITLE
Public Internet in html output

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-analyzer#815]
When the analysis concludes that there is no public connectivity, the html output does not contain the "public internet" node. In this case the user cannot explore the explanation of *why* public connectivity is blocked. 

We could add this node by default so it is always there. 
Another option is to add it if there is at least one public gateway or FIP in the entire solution (IBM), or at least one public subnet (AWS). This is under the assumption that an explanation will be required only if external connectivity is somehow blocked, not if it wasn't planned to begin with.

**Comment by haim-kermany** [comment]
I can add node that represent the range of the entire public internet. 
should I add also in case when there are external nodes? ( for cases that the external nodes represent only part of the public internet)
