### ISSUE TITLE
Handle AWS Instance status

### ISSUE THREAD

**Issue by kyorav** [np-guard/vpc-network-config-analyzer#849]
Instances in AWS may show up in the configuration object even after being terminated. The analyzer should only consider running instances, which will have the `State` property set as follows:
```
"State": {
    "Code": 16,
    "Name": "running"
}
```

**Comment by olasaadi99** [comment]
@zivnevo @kyorav 
it is already fixed right? about three weeks ago
`if instance.State.Name != types.InstanceStateNameRunning {
			continue
		}`

**Comment by olasaadi99** [comment]
https://github.com/np-guard/vpc-network-config-analyzer/issues/811

**Comment by zivnevo** [comment]
@kyorav , is this a duplicate of #811?

**Comment by kyorav** [comment]
yes
