### ISSUE TITLE
inconsistency in html graph w.r.t. external cidrs

### ISSUE THREAD

**Issue by ShiriMoran** [np-guard/vpc-network-config-analyzer#855]
At the moment, each node in the html graph for external ips is an endpoint which is a src/dst in a line of the textual presentation.
As a result:
1. A single external cidr may participate in several html nodes
2. The edges to/from a single external node may present only some of the connections of a cidrs that participates in this node. To get the full connectivity one need to consider all the nodes that the cidr participate in.
3. As a result of the above item, the explanantion for a specific node may actually be non-consistent with its edges. This is since the explainability will include all the existing connections.

Development wise, this is because the html graph is driven from the connectivity result grouped for external ips.

My proposed solution: have a dedicated grouping for drawio in which the grouping in such that each cidr is at most in one grouping line.
The issue with this solution is that it may result in too many "html nodes"
Perhaps have a default over approximation presentation of the entire internet and then enable restriction it to specifics, selected, cidrs?

@zivnevo @haim-kermany

**Comment by ShiriMoran** [comment]
After discussion with @haim-kermany 

Consider the following:
142.0.0.0/7 -> vsi1
142.0.0.0/8 -> vsi2
0.0.0.0/0 -> vsi3

transforming this to nodes with distinct cidrs will result in:
142.0.0.0/8 -> `vsi1`, `vsi2`,  `vsi3`
143.0.0.0-143.255.255.255 -> `vsi1`, `vsi3`
0.0.0.0 - 141.255.255.255, 144.0.0.0 - 255.255.255.255 -> `vsi3`

Which is clearly less readable and graphically will result in much more edges. Especially if we assume users will mainly want to know what is the public internet available for a certain `vsi` and not vice versa. Specifically, it will be much harder to see that vsi3 is accessible to the entire public internet
Solutions:
1. Transform to distinct cidrs as above
2. Leave as is, perhaps change the icon of `cidr` to something less strict, as cloud, that will imply it is not a node in the same strict manner the `vsi`s are.
3. Have 2 types of nodes: "entire public internet" and the other cidrs. In this option, the above will look as follows:
142.0.0.0/8 -> `vsi1`, `vsi2`
143.0.0.0-143.255.255.255 -> `vsi1`
0.0.0.0/0 -> vsi3
And sometime in the future present the entire internet not as a node but as the entire rectangle - have edges emerging from that rectangle.
This solution is much more readable than 1 and the nodes are well defined, in the sense that cidrs of different nodes are disjoint

Indeed, 1 seems like a bad solution. We should decide between 2 and 3 (and other ideas?). @haim-kermany strongly prefers `2`
@zivnevo @kyorav

**Comment by kyorav** [comment]
There is also option 4: instead of splitting nodes we add edges to represent ability to connect:
142.0.0.0/7 -> vsi1, vsi3
142.0.0.0/8 -> vsi2, vsi1, vsi3
0.0.0.0/0 -> vsi3

This is the most intuitive for me, but obviously this is very subjective. If option 4 is impossible (maybe it can't be generalized?) or too much work, then I'd choose 3 because it is at least accurate.

**Comment by ShiriMoran** [comment]
> There is also option 4: instead of splitting nodes we add edges to represent ability to connect: 142.0.0.0/7 -> vsi1, vsi3 142.0.0.0/8 -> vsi2, vsi1, vsi3 0.0.0.0/0 -> vsi3
> 
> This is the most intuitive for me, but obviously this is very subjective. If option 4 is impossible (maybe it can't be generalized?) or too much work, then I'd choose 3 because it is at least accurate.

If I understand you correctly, this is what we have today.  In the pic below the 2nd node is 142.0.0.0/7 and the issue is that one node actually contains the other, cidr wise. I don
![image](https://github.com/user-attachments/assets/fc89ac43-172d-4918-b907-c69b55ded2dc)

**Comment by ShiriMoran** [comment]
> There is also option 4: instead of splitting nodes we add edges to represent ability to connect: 142.0.0.0/7 -> vsi1, vsi3 142.0.0.0/8 -> vsi2, vsi1, vsi3 0.0.0.0/0 -> vsi3
> 
> This is the most intuitive for me, but obviously this is very subjective. If option 4 is impossible (maybe it can't be generalized?) or too much work, then I'd choose 3 because it is at least accurate.

I think this is too much work @haim-kermany  is it?

**Comment by ShiriMoran** [comment]
> There is also option 4: instead of splitting nodes we add edges to represent ability to connect: 142.0.64.0/17 -> vsi2, vsi, vsi3 142.0.0.0/16 -> vsi1, vsi3 0.0.0.0/0 -> vsi3
> 
> This is the most intuitive for me, but obviously this is very subjective. If option 4 is impossible (maybe it can't be generalized?) or too much work, then I'd choose 3 because it is at least accurate.

I think this is too much work @haim-kermany  is it?

**Comment by zivnevo** [comment]
Please recall that we already have a node for all public internet IPs - this is the big rectangle where all the CIDR icons live. The recent enhancements @haim-kermany made, allow selecting this rectangle for getting full details + explanation regarding connectivity to the internet. So maybe option 5 would be to leave just this rectangle (possibly, only if there are too many CIDRs inside and things get messy).

**Comment by ShiriMoran** [comment]
@nevo you mean leaving this rectangle and removing the "all internet" node?
This makes sense, but unless combining it with 3 or 4 we are left with a graph that is inconsistent.
Just to make sure we are all on the same page: the inconsistency problem with the current graph is that it is not a legal graph, in the sense that the edges from a specific external node could present only a subset of the actual edges from the cidr(s) it present. As `142.0.64.0/17 ->vsi2` in the example below.

I tend to think  @kyorav 's solution (which was also proposed by @zivnevo at some point) is the best:
1.  The graph is consistent; the edges from an external node are all the edges that apply to the entire IP range represented by the node
1. We do not add nodes
2. Looking at the nodes from a  VSI to external nodes, one can easily understand what this VSI is connected to (@haim-kermany )
3. Last and perhaps least, the amount of work required to implement the solution is not big

On top of this solution and independent from it, we can apply @zivnevo 's 5 above and remove the extra "all internet" node

**Comment by zivnevo** [comment]
> @nevo you mean leaving this rectangle and removing the "all internet" node? This makes sense, but unless combining it with 3 or 4 we are left with a graph that is inconsistent. Just to make sure we are all on the same page: the inconsistency problem with the current graph is that it is not a legal graph, in the sense that the edges from a specific external node could present only a subset of the actual edges from the `cidr`(s) it present. As `142.0.64.0/17 ->vsi2` in the example above.
> 

I meant that when things get too messy, leave just the rectangle with no icons in it. Users get less (graphical) details, but they can get these details (textually) if they select the rectangle and a VSI

**Comment by ShiriMoran** [comment]
> > @nevo you mean leaving this rectangle and removing the "all internet" node? This makes sense, but unless combining it with 3 or 4 we are left with a graph that is inconsistent. Just to make sure we are all on the same page: the inconsistency problem with the current graph is that it is not a legal graph, in the sense that the edges from a specific external node could present only a subset of the actual edges from the `cidr`(s) it present. As `142.0.64.0/17 ->vsi2` in the example above.
> 
> I meant that when things get too messy, leave just the rectangle with no icons in it. Users get less (graphical) details, but they can get these details (textually) if they select the rectangle and a VSI

makes sense; this can be on top of the other solution.
The problem with 3. is that I'm afraid it will make also the simple cases messier. This is why I tend to 4 + 5
